version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: burn
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin4@pgadmin.org"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - db
  nodejs:
    build:
      context: server/.
      dockerfile: ../Dockerfile
    image: nodejs
    # container_name: nodejs
    restart: unless-stopped
    ports:
      - "3000:3000"
